name: release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    container: kraftkit.sh/myself-full:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Fetch all tags
        run: |
          git config --global --add safe.directory /__w/governance/governance
          git fetch --force --tags

      - name: Run GoReleaser
        run: |
          goreleaser release \
            --config .goreleaser.yml \
            --clean \
            --skip=validate
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
